name: Deploy Spring Boot App to AKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker image
        run: docker build -t ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}:${{ github.sha }} .

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_COMMON }}

      - name: Push Docker image to ACR
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
          docker push ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}:${{ github.sha }}

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/${{ vars.APP_NAME }} ${{ vars.APP_NAME }}=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}:${{ github.sha }}
