name: Deploy Spring Boot App to VM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Maven settings.xml
        run: |
          cat <<EOF > ./settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_ADMIN_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Spring Boot app
        run: mvn -s settings.xml clean package

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_COMMON }}

      - name: Upload WAR file to Blob Storage
        run: |
          az storage blob upload \
            --account-name ${{ vars.AZURE_COMMON_STORAGE_ACCOUNT }} \
            --container-name ${{ vars.AZURE_COMMON_ARTIFACT_CONTAINER }} \
            --file target/*.war \
            --name ${{ vars.APP_NAME }}.war

      - name: Deploy to VM via SSH
        if: ${{ inputs.environment == 'dev' }}
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_IP_DEV }}
          username: ${{ vars.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY_DEV }}
          script: |
            sudo systemctl stop springboot-app
            sudo rm -rf /var/www/springboot-app/*.war
            sudo wget https://<blob-url>/${{ vars.AZURE_COMMON_ARTIFACT_CONTAINER }}/app.war -O /var/www/springboot-app/app.war
            sudo systemctl start springboot-app
